### ISSUE TITLE
Mongoose setup: make db name configurable

### ISSUE THREAD

**Issue by sthzg** [stylesuxx/generator-es6-graphql#2]
The generator defaults the database name to the project name specified in package.json, which might potentially lead to corrupting an existing database. A possible extra step could also be a db exists check during the generation resulting in an approval prompt if a db with the specified name exists.

**Comment by stylesuxx** [comment]
Not sure if it makes sense to check if a database exists on the system since the generated app may be deployed somewhere else. Will add a prompt to set the database name though.

**Comment by sthzg** [comment]
Not certain though that the generator would be run on the deploy target. So if the generator itself does anything to the DB that still may only apply to the dev-env. Anyways, having it configurable would be great.
